# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reg.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_table = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table.setGeometry(QtCore.QRect(0, 60, 563, 501))
        self.main_table.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(0)
        self.main_table.setRowCount(0)
        self.prev_eqs = QtWidgets.QListWidget(self.centralwidget)
        self.prev_eqs.setGeometry(QtCore.QRect(563, 60, 241, 501))
        self.prev_eqs.setObjectName("prev_eqs")
        self.bt_clear_selection = QtWidgets.QPushButton(self.centralwidget)
        self.bt_clear_selection.setGeometry(QtCore.QRect(0, 0, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_clear_selection.setFont(font)
        self.bt_clear_selection.setObjectName("bt_clear_selection")
        self.bt_eq_run = QtWidgets.QPushButton(self.centralwidget)
        self.bt_eq_run.setGeometry(QtCore.QRect(660, 0, 150, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_eq_run.setFont(font)
        self.bt_eq_run.setObjectName("bt_eq_run")
        self.bt_eq_reset = QtWidgets.QPushButton(self.centralwidget)
        self.bt_eq_reset.setGeometry(QtCore.QRect(560, 0, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_eq_reset.setFont(font)
        self.bt_eq_reset.setObjectName("bt_eq_reset")
        self.bt_all_selection = QtWidgets.QPushButton(self.centralwidget)
        self.bt_all_selection.setGeometry(QtCore.QRect(282, 0, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_all_selection.setFont(font)
        self.bt_all_selection.setObjectName("bt_all_selection")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_file_new = QtWidgets.QAction(MainWindow)
        self.menu_file_new.setObjectName("menu_file_new")
        self.menu_file_open = QtWidgets.QAction(MainWindow)
        self.menu_file_open.setObjectName("menu_file_open")
        self.menu_file_save = QtWidgets.QAction(MainWindow)
        self.menu_file_save.setObjectName("menu_file_save")
        self.menu_type_eq = QtWidgets.QAction(MainWindow)
        self.menu_type_eq.setObjectName("menu_type_eq")
        self.menu_type_bydots = QtWidgets.QAction(MainWindow)
        self.menu_type_bydots.setObjectName("menu_type_bydots")
        self.menu_type_reg = QtWidgets.QAction(MainWindow)
        self.menu_type_reg.setObjectName("menu_type_reg")
        self.menu_plot_build = QtWidgets.QAction(MainWindow)
        self.menu_plot_build.setObjectName("menu_plot_build")
        self.menu_plot_save = QtWidgets.QAction(MainWindow)
        self.menu_plot_save.setObjectName("menu_plot_save")
        self.menu_plot_sett = QtWidgets.QAction(MainWindow)
        self.menu_plot_sett.setObjectName("menu_plot_sett")
        self.menu_help = QtWidgets.QAction(MainWindow)
        self.menu_help.setObjectName("menu_help")
        self.menu.addAction(self.menu_file_new)
        self.menu.addAction(self.menu_file_open)
        self.menu.addAction(self.menu_file_save)
        self.menu_2.addAction(self.menu_type_eq)
        self.menu_2.addAction(self.menu_type_reg)
        self.menu_3.addAction(self.menu_plot_build)
        self.menu_3.addAction(self.menu_plot_save)
        self.menu_4.addAction(self.menu_help)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_clear_selection.setText(_translate("MainWindow", "Отчистить выделение"))
        self.bt_eq_run.setText(_translate("MainWindow", "Вычислить"))
        self.bt_eq_reset.setText(_translate("MainWindow", "Отчистить"))
        self.bt_all_selection.setText(_translate("MainWindow", "Выделить всё"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Тип"))
        self.menu_3.setTitle(_translate("MainWindow", "График"))
        self.menu_4.setTitle(_translate("MainWindow", "Помощь"))
        self.menu_file_new.setText(_translate("MainWindow", "Новый"))
        self.menu_file_open.setText(_translate("MainWindow", "Открыть"))
        self.menu_file_save.setText(_translate("MainWindow", "Сохранить"))
        self.menu_type_eq.setText(_translate("MainWindow", "Уравнение"))
        self.menu_type_bydots.setText(_translate("MainWindow", "По точкам"))
        self.menu_type_reg.setText(_translate("MainWindow", "Вычислить Уравнение"))
        self.menu_plot_build.setText(_translate("MainWindow", "Построить"))
        self.menu_plot_save.setText(_translate("MainWindow", "Сохранить"))
        self.menu_plot_sett.setText(_translate("MainWindow", "Настройки"))
        self.menu_help.setText(_translate("MainWindow", "Как пользоваться"))
