# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eq.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Eq_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Eq_edit.setGeometry(QtCore.QRect(0, 40, 801, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Eq_edit.setFont(font)
        self.Eq_edit.setText("")
        self.Eq_edit.setObjectName("Eq_edit")
        self.Eqlist = QtWidgets.QListWidget(self.centralwidget)
        self.Eqlist.setGeometry(QtCore.QRect(0, 170, 611, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Eqlist.setFont(font)
        self.Eqlist.setObjectName("Eqlist")
        self.Eqroots = QtWidgets.QListWidget(self.centralwidget)
        self.Eqroots.setGeometry(QtCore.QRect(610, 170, 191, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Eqroots.setFont(font)
        self.Eqroots.setObjectName("Eqroots")
        self.Eadd = QtWidgets.QPushButton(self.centralwidget)
        self.Eadd.setGeometry(QtCore.QRect(240, 110, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Eadd.setFont(font)
        self.Eadd.setObjectName("Eadd")
        self.Edelete = QtWidgets.QPushButton(self.centralwidget)
        self.Edelete.setGeometry(QtCore.QRect(400, 110, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Edelete.setFont(font)
        self.Edelete.setObjectName("Edelete")
        self.lb_roots = QtWidgets.QLabel(self.centralwidget)
        self.lb_roots.setGeometry(QtCore.QRect(610, 110, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_roots.setFont(font)
        self.lb_roots.setTextFormat(QtCore.Qt.AutoText)
        self.lb_roots.setObjectName("lb_roots")
        self.lb_list = QtWidgets.QLabel(self.centralwidget)
        self.lb_list.setGeometry(QtCore.QRect(10, 125, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_list.setFont(font)
        self.lb_list.setObjectName("lb_list")
        self.lb_edit = QtWidgets.QLabel(self.centralwidget)
        self.lb_edit.setGeometry(QtCore.QRect(10, 0, 771, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_edit.setFont(font)
        self.lb_edit.setObjectName("lb_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_file_new = QtWidgets.QAction(MainWindow)
        self.menu_file_new.setObjectName("menu_file_new")
        self.menu_file_open = QtWidgets.QAction(MainWindow)
        self.menu_file_open.setObjectName("menu_file_open")
        self.menu_file_save = QtWidgets.QAction(MainWindow)
        self.menu_file_save.setObjectName("menu_file_save")
        self.menu_type_eq = QtWidgets.QAction(MainWindow)
        self.menu_type_eq.setObjectName("menu_type_eq")
        self.menu_type_bydots = QtWidgets.QAction(MainWindow)
        self.menu_type_bydots.setObjectName("menu_type_bydots")
        self.menu_type_reg = QtWidgets.QAction(MainWindow)
        self.menu_type_reg.setObjectName("menu_type_reg")
        self.menu_plot_build = QtWidgets.QAction(MainWindow)
        self.menu_plot_build.setObjectName("menu_plot_build")
        self.menu_plot_save = QtWidgets.QAction(MainWindow)
        self.menu_plot_save.setObjectName("menu_plot_save")
        self.menu_plot_sett = QtWidgets.QAction(MainWindow)
        self.menu_plot_sett.setObjectName("menu_plot_sett")
        self.menu_help = QtWidgets.QAction(MainWindow)
        self.menu_help.setObjectName("menu_help")
        self.menu.addAction(self.menu_file_new)
        self.menu.addAction(self.menu_file_open)
        self.menu.addAction(self.menu_file_save)
        self.menu_2.addAction(self.menu_type_eq)
        self.menu_2.addAction(self.menu_type_reg)
        self.menu_3.addAction(self.menu_plot_build)
        self.menu_3.addAction(self.menu_plot_save)
        self.menu_3.addAction(self.menu_plot_sett)
        self.menu_4.addAction(self.menu_help)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Eadd.setText(_translate("MainWindow", "Добавить"))
        self.Edelete.setText(_translate("MainWindow", "Удалить"))
        self.lb_roots.setText(_translate("MainWindow",
                                         " Приблизительные\n "
                                         "точки пересечения"))
        self.lb_list.setText(_translate("MainWindow", "Текущие уравнения"))
        self.lb_edit.setText(_translate("MainWindow", "Уравнение"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Тип"))
        self.menu_3.setTitle(_translate("MainWindow", "График"))
        self.menu_4.setTitle(_translate("MainWindow", "Помощь"))
        self.menu_file_new.setText(_translate("MainWindow", "Новый"))
        self.menu_file_open.setText(_translate("MainWindow", "Открыть"))
        self.menu_file_save.setText(_translate("MainWindow", "Сохранить"))
        self.menu_type_eq.setText(_translate("MainWindow", "Уравнение"))
        self.menu_type_bydots.setText(_translate("MainWindow", "По точкам"))
        self.menu_type_reg.setText(_translate("MainWindow",
                                              "Вычислить уравнение"))
        self.menu_plot_build.setText(_translate("MainWindow", "Построить"))
        self.menu_plot_save.setText(_translate("MainWindow", "Сохранить"))
        self.menu_plot_sett.setText(_translate("MainWindow", "Настройки"))
        self.menu_help.setText(_translate("MainWindow", "Как пользоваться"))
